#!/bin/bash
#===============================================================================
# Guide de Déploiement Rapide vers Production
#===============================================================================

echo "==================================================="
echo "  Déploiement des Nouvelles Fonctionnalités"
echo "==================================================="
echo ""
echo "Les changements sont prêts dans Git mais doivent être"
echo "déployés sur votre serveur de production."
echo ""

# Étape 1
echo "📦 ÉTAPE 1 : Fusionner la branche (sur GitHub)"
echo "────────────────────────────────────────────────"
echo "1. Allez sur GitHub :"
echo "   https://github.com/eme-data/prospection/pull/new/claude/viabilis-map-evolution-brBkE"
echo ""
echo "2. Créez la Pull Request"
echo ""
echo "3. Mergez dans votre branche principale (main/master)"
echo ""

# Étape 2
echo "🚀 ÉTAPE 2 : Déployer sur votre serveur"
echo "────────────────────────────────────────────────"
echo "Connectez-vous à votre serveur de production :"
echo ""
echo "ssh votre-utilisateur@votre-serveur.com"
echo ""
echo "Puis exécutez :"
echo ""
echo "cd /opt/prospection"
echo "sudo ./update.sh"
echo ""
echo "OU si update.sh n'existe pas encore :"
echo ""
echo "sudo systemctl stop prospection"
echo "sudo -u prospection git pull origin main"
echo "sudo -u prospection docker compose build --no-cache"
echo "sudo systemctl start prospection"
echo ""

# Alternative
echo "📋 ALTERNATIVE : Déploiement depuis une branche spécifique"
echo "────────────────────────────────────────────────"
echo "Si vous voulez déployer directement la branche sans merger :"
echo ""
echo "cd /opt/prospection"
echo "sudo systemctl stop prospection"
echo "sudo -u prospection git fetch origin"
echo "sudo -u prospection git checkout claude/viabilis-map-evolution-brBkE"
echo "sudo -u prospection git pull origin claude/viabilis-map-evolution-brBkE"
echo "sudo -u prospection docker compose build --no-cache"
echo "sudo systemctl start prospection"
echo ""

# Vérification
echo "✅ VÉRIFICATION après déploiement"
echo "────────────────────────────────────────────────"
echo "curl http://votre-serveur.com/health"
echo "sudo docker compose logs -f"
echo "sudo docker compose ps"
echo ""

# Informations
echo "📝 INFORMATIONS"
echo "────────────────────────────────────────────────"
echo "Commit actuel : c536279"
echo "Branche       : claude/viabilis-map-evolution-brBkE"
echo "Version       : v2.1.0"
echo ""
echo "Nouvelles fonctionnalités :"
echo "  - 📁 Gestion de projets"
echo "  - 📊 Dashboard avec graphiques"
echo "  - 🔔 Historique & alertes"
echo "  - 📄 Rapports PDF"
echo "  - 🌍 Données enrichies"
echo "  - 🎨 Mode sombre/clair"
echo ""
echo "==================================================="
